## Example config file.

# The bot's token to run with.
token: xcqyegftw

# A list of plugins to autoload.
autoload:
  - jokusoramame.plugins.core
  - jokusoramame.plugins.levelling

redis:
  host: 127.0.0.1
  port: 6379