"""
Autogenerated migration file.

Revision: 1
Message: Initial migration
"""
from asyncqlio import Session

revision = "1"
message = "Initial migration"


async def upgrade(session: Session):
    """
    Performs an upgrade. Put your upgrading SQL here.
    """
    await session.execute("""    
    CREATE TABLE user_xp (
        id SERIAL PRIMARY KEY,
        user_id BIGINT,
        guild_id BIGINT NOT NULL,
        xp INTEGER NOT NULL DEFAULT 0,
        level INTEGER NOT NULL DEFAULT 1,
        UNIQUE (user_id, guild_id)
    );
    
    CREATE INDEX user_xp_user_id_idx ON user_xp (user_id);
    CREATE INDEX user_xp_guild_id_idx ON user_xp (guild_id);
    CREATE INDEX user_xp_xp_idx ON user_xp (xp);
    CREATE INDEX user_xp_level_idx ON user_xp (level);
    """)


async def downgrade(session: Session):
    """
    Performs a downgrade. Put your downgrading SQL here.
    """
    await session.execute("""
    DROP TABLE user_xp CASCADE;
    DROP TABLE "user_xp" CASCADE;
    """)
