"""
Autogenerated migration file.

Revision: 2
Message: Add rolestate and guildsettings
"""
from asyncqlio import Session

revision = "2"
message = "Add rolestate and guildsettings"


async def upgrade(session: Session):
    """
    Performs an upgrade. Put your upgrading SQL here.
    """
    await session.execute("""
    CREATE TABLE guild_setting (
      id SERIAL PRIMARY KEY,
      guild_id BIGINT NOT NULL,
      name TEXT NOT NULL,
      value TEXT NOT NULL
    );
    
    CREATE TABLE rolestate (
      id SERIAL PRIMARY KEY,
      user_id BIGINT NOT NULL,
      guild_id BIGINT NOT NULL,
      roles TEXT,
      nick TEXT
    );
    
    CREATE UNIQUE INDEX rolestate_uid_gid_idx ON rolestate (user_id, guild_id);
    CREATE UNIQUE INDEX guild_setting_gid_name_idx ON guild_setting (guild_id, name);
    """)


async def downgrade(session: Session):
    """
    Performs a downgrade. Put your downgrading SQL here.
    """
    await session.execute("DROP TABLE guild_setting; DROP TABLE rolestate;")
