"""
Autogenerated migration file.

Revision: 4
Message: Add user balances.
"""
from asyncqlio.orm.ddl.ddlsession import DDLSession

revision = "4"
message = "Add user balances."


async def upgrade(session: DDLSession):
    """
    Performs an upgrade. Put your upgrading SQL here.
    """
    await session.execute("""
    CREATE TABLE user_balance (
        id SERIAL PRIMARY KEY,
        user_id BIGINT,
        guild_id BIGINT NOT NULL,
        money INTEGER NOT NULL DEFAULT 0
    );

    CREATE INDEX user_balance_user_id_idx ON user_balance (user_id);
    CREATE INDEX user_balance_guild_id_idx ON user_balance (guild_id);
    CREATE INDEX user_balance_money_idx ON user_balance (money);
    """)


async def downgrade(session: DDLSession):
    """
    Performs a downgrade. Put your downgrading SQL here.
    """
    await session.execute("""
    DROP TABLE user_balance;
    """)
