"""
Autogenerated migration file.

Revision: 5
Message: Add colourme field to RolemeRole
"""
from asyncqlio import Session

revision = "5"
message = "Add colourme field to RolemeRole"


async def upgrade(session: Session):
    """
    Performs an upgrade. Put your upgrading SQL here.
    """
    await session.execute("""
    ALTER TABLE roleme_role ADD COLUMN colourme BOOLEAN DEFAULT FALSE;
    """)


async def downgrade(session: Session):
    """
    Performs a downgrade. Put your downgrading SQL here.
    """
    await session.execute("""
    ALTER TABLE roleme_role DROP COLUMN colourme;
    """)
