"""OAuth2 start

Revision ID: 0a2ba8dce059
Revises: 9f50538504b1
Create Date: 2017-02-11 13:48:45.564677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a2ba8dce059'
down_revision = '9f50538504b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_token', postgresql.JSONB(astext_type=Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'oauth_token')
    # ### end Alembic commands ###
