"""Change Rolestate roles array to ARRAY[BigInteger]

Revision ID: 1da99da59d35
Revises: e86b741dc3fc
Create Date: 2017-02-04 15:08:46.643476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da99da59d35'
down_revision = 'e86b741dc3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("ALTER TABLE rolestate ALTER COLUMN roles TYPE BIGINT[]")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("ALTER TABLE rolestate ALTER COLUMN roles TYPE INTEGER[]")
    # ### end Alembic commands ###
