"""settings table to settings hstore

Revision ID: 446f63745da6
Revises: 9a0f78ff57d6
Create Date: 2017-04-28 15:20:09.487526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '446f63745da6'
down_revision = '9a0f78ff57d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    op.create_unique_constraint('tag_alias_id_key', 'tag_alias', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_alias_id_key', 'tag_alias', type_='unique')
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='setting_guild_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='setting_pkey')
    )
    # ### end Alembic commands ###
