"""Add bulletin_message field to Guild.

Revision ID: 5524aa0ee0e6
Revises: afc57bd04606
Create Date: 2017-03-14 20:09:19.814213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5524aa0ee0e6'
down_revision = 'afc57bd04606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('bulletin_message', sa.BigInteger(), nullable=True))
    op.drop_column('guild', 'stock_announcement_id')
    op.drop_column('rolestate', 'overwrites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolestate', sa.Column('overwrites', postgresql.HSTORE(text_type=Text()), autoincrement=False, nullable=True))
    op.add_column('guild', sa.Column('stock_announcement_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('guild', 'bulletin_message')
    # ### end Alembic commands ###
