"""Unique was a mistake

Revision ID: 5b75f2df4f50
Revises: c877a04b8181
Create Date: 2017-02-05 11:45:45.397934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b75f2df4f50'
down_revision = 'c877a04b8181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tag', ['id'])
    op.drop_constraint('user_colour_role_id_key', 'user_colour', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_colour_role_id_key', 'user_colour', ['role_id'])
    op.drop_constraint(None, 'tag', type_='unique')
    # ### end Alembic commands ###
