"""Add Channel to EventSetting

Revision ID: 62b3c37ee7e3
Revises: b3a672162cc0
Create Date: 2017-02-05 00:31:53.437256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b3c37ee7e3'
down_revision = 'b3a672162cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_setting', sa.Column('channel_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_setting', 'channel_id')
    # ### end Alembic commands ###
