"""Add lots of models

Revision ID: 7cb3cc8cc18b
Revises: 1da99da59d35
Create Date: 2017-02-04 20:46:41.924579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import BigInteger
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cb3cc8cc18b'
down_revision = '1da99da59d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('roleme_roles', postgresql.ARRAY(BigInteger()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_foreign_key(None, 'rolestate', 'guild', ['guild_id'], ['id'])
    op.create_foreign_key(None, 'setting', 'guild', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setting', type_='foreignkey')
    op.drop_constraint(None, 'rolestate', type_='foreignkey')
    op.drop_table('guild')
    op.drop_table('event_setting')
    # ### end Alembic commands ###
