"""Add bulletin_message field to Guild.

Revision ID: 8010376daba7
Revises: afc57bd04606
Create Date: 2017-03-14 20:32:02.467432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8010376daba7'
down_revision = 'afc57bd04606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('announcement_channel', sa.BigInteger(), nullable=True))
    op.add_column('guild', sa.Column('bulletin_channel', sa.BigInteger(), nullable=True))
    op.add_column('guild', sa.Column('bulletin_message', sa.BigInteger(), nullable=True))
    op.drop_column('guild', 'stock_announcement_id')
    op.drop_column('rolestate', 'overwrites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolestate', sa.Column('overwrites', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('guild', sa.Column('stock_announcement_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('guild', 'bulletin_message')
    op.drop_column('guild', 'bulletin_channel')
    op.drop_column('guild', 'announcement_channel')
    # ### end Alembic commands ###
