"""Add property to see if stocks are enabled on a guild.

Revision ID: 9c8ce0562634
Revises: c4af88def97b
Create Date: 2017-02-18 01:42:03.857883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8ce0562634'
down_revision = 'c4af88def97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('stocks_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild', 'stocks_enabled')
    # ### end Alembic commands ###
