"""Add correct foreign key to EventSetting

Revision ID: 9da95f53e8a1
Revises: 7cb3cc8cc18b
Create Date: 2017-02-04 20:58:52.294283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da95f53e8a1'
down_revision = '7cb3cc8cc18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_setting', sa.Column('guild_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'event_setting', 'guild', ['guild_id'], ['id'])
    op.create_unique_constraint(None, 'guild', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guild', type_='unique')
    op.drop_constraint(None, 'event_setting', type_='foreignkey')
    op.drop_column('event_setting', 'guild_id')
    # ### end Alembic commands ###
