"""Add InventoryItem class.

Revision ID: b68e0d8ed9fe
Revises: 80e470911917
Create Date: 2017-02-03 23:19:40.082764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68e0d8ed9fe'
down_revision = '80e470911917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_inv_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('count', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('user_inv_item')
    # ### end Alembic commands ###
