"""colourme array and settings hstore

Revision ID: b9286b9eae48
Revises: 446f63745da6
Create Date: 2017-04-28 15:28:16.990013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9286b9eae48'
down_revision = '446f63745da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('colourme_roles', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=True))
    op.add_column('guild', sa.Column('settings', postgresql.HSTORE(text_type=sa.Text()), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild', 'settings')
    op.drop_column('guild', 'colourme_roles')
    # ### end Alembic commands ###
