"""Change money field to BigInteger

Revision ID: c4af88def97b
Revises: 0a2ba8dce059
Create Date: 2017-02-13 22:47:02.959306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4af88def97b'
down_revision = '0a2ba8dce059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute('ALTER TABLE "user" ALTER COLUMN money TYPE BIGINT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute('ALTER TABLE "user" ALTER COLUMN money TYPE INT')
    # ### end Alembic commands ###
