"""Add lua field to Tag.

Revision ID: d19881f4c045
Revises: 8010376daba7
Create Date: 2017-03-19 12:46:19.842382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19881f4c045'
down_revision = '8010376daba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('lua', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'lua')
    # ### end Alembic commands ###
